export const events = [
  {
    title: 'Hacktoberfest Kick-Off',
    content: 'The official beginning of Hacktoberfest. Join DigitalOcean developers as we begin the month-long hacking event you’ve been waiting for.',
    location: 'Online',
    date: 'Oct 04',
    time: '11:00 AM Eastern Daylight Time',
    format: ['Livestream'],
    rsvp: null,
  },
  {
    title: 'Hacktoberfest Hack Party Asia Pacific Edition',
    content: 'Get started with non-code contributions to Hacktoberfest no matter your experience level.',
    location: 'Online',
    date: 'Oct 12',
    time: '11:00 AM Indian Standard Time',
    format: ['Livestream'],
    rsvp: null,
  },
  {
    title: 'Hacktoberfest Hack Party',
    content: '',
    location: 'Online',
    date: 'Oct 20',
    time: 'TBD',
    format: ['Livestream'],
    rsvp: null,
  },
  {
    title: 'Hacktoberfest Wrap Party',
    content: '',
    location: 'Online',
    date: 'Oct 27',
    time: '11:00 AM Eastern Daylight Time',
    format: ['Livestream'],
    rsvp: null,
  },
];
