"""Regenerates src/data/worldGrid.mjs, the land behind the homepage's Fest
map: which cells of a coarse equirectangular grid are land.

It only needs re-running if the grid's shape changes (columns, or the
bounds below), which also moves every Fest square, so change both together.
The land data comes from the global-land-mask package (MIT, derived from
GLOBE 1km elevation data):

    python3 -m venv /tmp/world-grid && /tmp/world-grid/bin/pip install global-land-mask
    /tmp/world-grid/bin/python scripts/world-grid.py > src/data/worldGrid.mjs
    npx prettier --write src/data/worldGrid.mjs
"""
from global_land_mask import globe

COLS = 128
# Antarctica and the high Arctic hold no Fests and would only push the
# inhabited continents together, so the band stops at 76N and 46S. The
# western edge sits at 170W, not the antimeridian, so Alaska and the
# Pacific islands east of it stay in one piece.
NORTH, SOUTH, WEST, EAST = 76, -46, -170, 190
ROWS = round(COLS * (NORTH - SOUTH) / (EAST - WEST))


def is_land(lat, lon):
    lon = lon - 360 if lon > 180 else lon
    return globe.is_land(lat, max(-180, min(180, lon)))


def main():
    dlon = (EAST - WEST) / COLS
    dlat = (NORTH - SOUTH) / ROWS
    rows = []
    for r in range(ROWS):
        row = ''
        for c in range(COLS):
            lat = NORTH - (r + 0.5) * dlat
            lon = WEST + (c + 0.5) * dlon
            # A cell is land when at least two of five points in it are,
            # which keeps narrow coasts and islands without inflating them.
            points = [(lat, lon)] + [(lat + dy * dlat * 0.3, lon + dx * dlon * 0.3)
                                     for dy in (-1, 1) for dx in (-1, 1)]
            row += '#' if sum(is_land(la, lo) for la, lo in points) >= 2 else '.'
        rows.append(row)
    body = ',\n'.join(f"    '{row}'" for row in rows)
    print(f"""/* The land behind the homepage's Fest map (components/FestMap): a
   {COLS} x {ROWS} equirectangular grid from {NORTH}N to {-SOUTH}S, starting at
   {-WEST}W and running east once round the world, one character per cell,
   '#' for land. Generated by scripts/world-grid.py; do not edit by hand. */
export const WORLD_GRID = Object.freeze({{
  cols: {COLS},
  rows: {ROWS},
  north: {NORTH},
  south: {SOUTH},
  west: {WEST},
  east: {EAST},
  land: Object.freeze([
{body},
  ]),
}});""")


main()
