#!/usr/bin/env node
/* Builds the designed stickers (catalogue.mjs + compose.mjs) and writes
   them where they are used:

   - by default, as a Figma development plugin at
     ~/Figma/HF26 sticker import/ (or --out <dir>): manifest.json and a
     code.js that carries every sticker and, when run in the HF26 design
     file, fills each frame of the Sticker grid by slug. Figma keeps
     pointing at that folder once the manifest is imported (Plugins ->
     Development -> Import plugin from manifest), so a rerun of the plugin
     picks up whatever was built last. `npm run stickers:figma`.
   - with --site, also into public/stickers/<slug>.svg, the files the site
     serves; scripts/stickers/render.mjs never overwrites them.

   The icon files are vendored in ./icons: Tabler's filled set
   (https://tabler.io/icons, MIT), plus the DEV badge. */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CATALOGUE, GROUNDS } from './catalogue.mjs';
import { composeSticker } from './compose.mjs';

const here = fileURLToPath(new URL('.', import.meta.url));

/* An icon file's paths, its viewBox size, and its fill rule if it sets
   one (a partner mark may cut its holes with even-odd). */
const readIcon = async (name) => {
  const svg = await readFile(join(here, 'icons', `${name}.svg`), 'utf8');
  const tags = [...svg.matchAll(/<path[^>]*?\sd="([^"]+)"[^>]*>/g)];
  const role = (m) => (m[0].match(/data-role="([^"]+)"/) || [])[1];
  const own = tags.filter((m) => !role(m));
  const fillers = tags.filter((m) => role(m) === 'filler').map((m) => m[1]);
  const lines = tags.filter((m) => role(m) === 'line').map((m) => m[1]);
  const paths = own.map((m) => m[1]);
  /* A path's own fill, kept for a partner mark drawn in its colours.
     Tabler's `currentColor` is not a colour: in an <img> it resolves to
     black and would paint over the white. */
  const paints = own.map((m) => {
    const fill = m[0].match(/\sfill="([^"]+)"/);
    return fill && fill[1] !== 'currentColor' ? fill[1] : undefined;
  });
  const silhouette = tags
    .filter((m) => role(m) === 'silhouette')
    .map((m) => m[1]);
  if (!paths.length) throw new Error(`no paths in icons/${name}.svg`);
  const viewBox = svg.match(/viewBox="([^"]+)"/);
  const [, , w, h] = (viewBox ? viewBox[1] : '0 0 24 24')
    .split(/\s+/)
    .map(Number);
  const rule = svg.match(/fill-rule="([^"]+)"/);
  const joinStyle = svg.match(/data-join="([^"]+)"/);
  const offset = svg.match(/data-offset="([^"]+)"/);
  return {
    paths,
    box: { w, h },
    fillRule: rule ? rule[1] : undefined,
    join: joinStyle ? joinStyle[1] : undefined,
    paints: paints.some(Boolean) ? paints : undefined,
    silhouette: silhouette.length ? silhouette : undefined,
    fillers: fillers.length ? fillers : undefined,
    lines: lines.length ? lines : undefined,
    offset: offset ? offset[1].split(/\s+/).map(Number) : undefined,
  };
};

export const buildStickers = async () => {
  const glyphs = JSON.parse(
    await readFile(join(here, 'martian-mono-glyphs.json'), 'utf8'),
  );
  const out = {};
  for (const entry of CATALOGUE) {
    const icon = await readIcon(entry.icon);
    out[entry.slug] = composeSticker({
      entry,
      iconPaths: icon.paths,
      iconBox: icon.box,
      iconFillRule: icon.fillRule,
      iconJoin: icon.join,
      iconPaints: icon.paints,
      iconSilhouette: icon.silhouette,
      iconFillers: icon.fillers,
      iconLines: icon.lines,
      iconOffset: icon.offset,
      footIcon: entry.foot ? await readIcon(entry.foot) : undefined,
      tagIcon: entry.tag ? await readIcon(entry.tag) : undefined,
      insetIcon: entry.inset ? await readIcon(entry.inset.icon) : undefined,
      ground: GROUNDS[entry.ground],
      glyphs,
    });
  }
  return out;
};

/* The plugin's code: plain Figma Plugin API, no build step. Frames are
   found by name under their cell (the grid names a frame by slug and its
   column "<slug> (cell)"), the guide hexagon is hidden, earlier art is
   removed, and the sticker is imported at 0,0. */
const pluginCode = (
  stickers,
) => `// HF26 sticker import, generated by scripts/stickers/design/build.mjs. Do not edit; rebuild.
const STICKERS = ${JSON.stringify(stickers)};
async function main() {
  let page = figma.currentPage;
  if (page.name !== 'Stickers') {
    const stickers = figma.root.children.find((n) => n.name === 'Stickers');
    if (stickers) { await figma.setCurrentPageAsync(stickers); page = stickers; }
  }
  let filled = 0;
  const missing = [];
  for (const [slug, svg] of Object.entries(STICKERS)) {
    const frame = page.findOne((n) => n.type === 'FRAME' && n.name === slug && n.parent && n.parent.name === slug + ' (cell)');
    if (!frame) { missing.push(slug); continue; }
    for (const child of [...frame.children]) {
      if (child.name === 'hexagon') child.visible = false;
      else if (child.name.startsWith('art')) child.remove();
    }
    const art = figma.createNodeFromSvg(svg);
    art.name = 'art';
    frame.appendChild(art);
    art.x = 0;
    art.y = 0;
    filled += 1;
  }
  figma.closePlugin('Filled ' + filled + ' of ' + Object.keys(STICKERS).length + ' frames' + (missing.length ? '; not found: ' + missing.join(', ') : ''));
}
main();
`;

const MANIFEST = {
  name: 'HF26 sticker import',
  id: '1758470000000000001',
  api: '1.0.0',
  main: 'code.js',
  editorType: ['figma'],
  documentAccess: 'dynamic-page',
  networkAccess: { allowedDomains: ['none'] },
};

const main = async () => {
  const args = process.argv.slice(2);
  const outFlag = args.indexOf('--out');
  const outDir =
    outFlag >= 0
      ? args[outFlag + 1]
      : join(homedir(), 'Figma', 'HF26 sticker import');
  const stickers = await buildStickers();

  await mkdir(outDir, { recursive: true });
  await writeFile(
    join(outDir, 'manifest.json'),
    `${JSON.stringify(MANIFEST, null, 2)}\n`,
  );
  await writeFile(join(outDir, 'code.js'), pluginCode(stickers));
  console.log(
    `figma plugin: ${Object.keys(stickers).length} stickers -> ${outDir}`,
  );

  if (args.includes('--site')) {
    const dir = new URL('../../../public/stickers/', import.meta.url);
    for (const [slug, svg] of Object.entries(stickers))
      await writeFile(new URL(`${slug}.svg`, dir), svg);
    console.log(
      `site: ${Object.keys(stickers).length} files -> public/stickers`,
    );
  }
};

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
